version: "3.1"
services:
  frontend:
    env_file:
      - .env
    build: frontend
    depends_on:
      - backend
    volumes:
      - ./frontend:/home/node/app
    expose:
      - "${PORT}"
  backend:
    env_file:
      - .env
    build: backend
    depends_on:
      - db
    volumes:
      - ./backend:/home/node/app
    expose:
      - "${PORT}"
  db:
    image: mongo:latest
    env_file:
      - .env
    restart: always
  proxy:
    build: .nginx
    env_file:
      - .env
    depends_on:
      - frontend
      - backend
    ports:
      - "${PORT}:${PORT}"
    restart: always
