version: "3.1"
services:
  frontend:
    image: node:lts-alpine
    env_file:
      - .env
    depends_on:
      - backend
    working_dir: /home/node/app
    volumes:
      - ./frontend:/home/node/app
    command: /bin/sh -c "npm i && npm start"
    user: node
    expose:
      - "${PORT}"
  backend:
    image: node:lts-alpine
    env_file:
      - .env
    depends_on:
      - mongo
    working_dir: /home/node/app
    volumes:
      - ./backend:/home/node/app
    command: /bin/sh -c "npm i && npm start"
    user: node
    expose:
      - "${PORT}"
  mongo:
    image: mongo:latest
    env_file:
      - .env
    ports:
      - 27017:27017
    restart: always
  nginx:
    build: .nginx
    env_file:
      - .env
    depends_on:
      - frontend
      - backend
    ports:
      - "${PORT}:${PORT}"
    restart: always
