version: "3.1"
services:
  frontend:
    env_file:
      - .env
    build: frontend
    depends_on:
      - backend
    volumes:
      - ./frontend:/home/node/app
    expose:
      - "${PORT}"
  backend:
    env_file:
      - .env
    build: backend
    depends_on:
      - mongo
    volumes:
      - ./backend:/home/node/app
    expose:
      - "${PORT}"
  mongo:
    image: mongo:latest
    env_file:
      - .env
    ports:
      - 27017:27017
    restart: always
  nginx:
    build: .nginx
    env_file:
      - .env
    depends_on:
      - frontend
      - backend
    ports:
      - "${PORT}:${PORT}"
    restart: always
