version: "3.1"
services:
  frontend:
    env_file:
      - .env
    build: frontend
    depends_on:
      - backend
    volumes:
      - ./frontend:/usr/src/app
      - appmodules:/usr/src/app/node_modules
  backend:
    env_file:
      - .env
    build: backend
    depends_on:
      - db
    volumes:
      - ./backend:/usr/src/app
      - servermodules:/usr/src/app/node_modules
  db:
    image: mongo:latest
    env_file:
      - .env
    restart: always
  proxy:
    build:
      context: ./.nginx
    env_file:
      - .env
    depends_on:
      - frontend
      - backend
    ports:
      - "${PORT}:${PORT}"
    restart: always
volumes:
  appmodules: {}
  servermodules: {}
